# .travis.yml
language: android
jdk: oraclejdk7
sudo: false
env:
  global:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
  - ADB_INSTALL_TIMEOUT=10

  - secure: NWjCzjh7odNCmn5KRkNPuC3jSMAWMRUyR8baKCDewxItrpUyAc8lFuMjQj9y5g9a8xCZ19ld3bZRMy9Qk2PZj8DJgbFlZKLkDr03dVVi0qoF096v9wu5EH9amMaiY+liFPtNGPSaqYbAWPVbAu1GUMmK1D0vfkHUWXPEzsHa1YTE/Pk5G4yGM25pdZtuslUMFfhSU3tQYypl4jaf2UtfiwqppXxKhaeXSg4IoVXV96m7wsjI2fJI/lSMZB8Wg6yrUSdCaAhIR+FvUcEOWIBaaxl83SKlhM/km/U9ZdWFlP4b9Ry5HSiFIId31LFRhpuBF9juPakknFTzLuLKoJ6o+PsIXGjFYV6AvHwRydcJtSWb/g2FZFfxv995c1PBRUK3yYT8snTZgTYPwoOTEW9JPvDAMOiDFl33NwP4pCSq8k1Ibw6EdmdHyk1nfOo+hTDRQfeffCNIwU+5USP7hjKJ6E82+u98kpgjb7AqYQN9HWmDRL5gcXyTR/sVKf1E7z+xac/4q3wcuG7/q9r1YsJlD/YRFHunKRtiI3wcUVDlHCHr0LLzKAPSluokx2TptaNoO4djB1jwpcUZgr3oAC5TNgPcu/AY9QyACtLlu78UjGbrYP48/ryW5Dicqs4O9M5OuIEKrds5hJOHxjP0wouSMyVx/jlgz6utKF35udI1aBs=
  - secure: dNB9z1UMDdMHWJpwJYygNxramD0/g4YAYmU9L1rOCi4y0dH72XNsU0VkXc5sX4u6kj0v3mI4Mv7vr9LLAOfgWmn9UKgj90sQRtk7ZXfDteY6sy/oXG1HzB45vwafqaaGILzGGIamx5WQUAJQU/RXqwHNMVS7zSk86pbqN8MPcKhgFqHtfteFVi5NspK05qHYLttZxyosEx/Okz4xXMHzYZVz5rZ+VVHF+UjFys+rzdW+l/gEpi90Vgo55pXs+NheKYIyhRq6IEdLG00ipHWEqZoVxtr/ZR6W+II3A4GLQz7GN25PjrD74dwNQd+0K0l7gX/3YyuhiqCBtu4eQovPXHNJYlXSgK29/KtMYl5YrDY37pq79RaQpo52EU9myTiG1AFDUtu3gN7tF5OwE89eBsAHDxv++3BOee1S+//qF+sRR5LFkJylBb1ox1hG2WVsg8thF7w8dopTTb9tQUgw/I1vrgvpewNApHiVHyw4DC6IOAN4t+zEyXAmQMi84havJslr8rbq9rVRDkXAqfX0CmuZb0TfeoCGCBA1b5YquyRGJQ/zPkFSaVSK1BUeTHRNAu2mzfjQc0hgqaez4e5L+367aSOYSzGUWyz/r26uH3/2yda2nhVxtLAylRNtiIoTuXmfWWrL1nohy/NFYGnVCVmwXXrelr42uLCemeQ3f9k=
  - secure: dK0ZbY2LotUPDpKMWJR6goqn07TjQstxYPWdkctwX01RkqcpvBQMjNqi6mITAuwcgZtda/3KXTpU9dHXoocCRIZCsTFuRbSDlTkUcgvmIZsq0t91s/04FHjRw4fDK57JENAS52ptfImasV7EmunKAW4J4689BoaY9ESGdacweuBnfi3ygWbUgnr8LaGbdOA/O02Mnj19Tj+F5rqKnVhE9kH4P6fPM0bua/2G139FTJl4Uv27EHZhnkobj8BE3aQDuVn9+RQta6QWhVtdFow/gMAn2PmPJ8hj+jn7wylDHdHqCCPkIlF3J5wbC0/UqgxhchTHq/IO4RFCPJ6aQaKstAG1p8PHTi/YkU5FTXgeigrH+a6fG3Jbvp9uXSlWonh//ehf1U0vmDSlvjRredVwGmOeyRk/2QcVmNFJ9RlYMpcY/4KwOiWqogR3itRoahNkMk+vILC63NQ+liFQMYiNyQibBQFjBFdY/TnA+JS+9GuVIpOx0jqNgLZLOgfHOThVQe7qfhRqY2P05/Gquw7n/YcK5fa2uL4tOgAKePe9gv97rr1Pg9VcJ2ku6nlrM4zoncCsWE6U2fPZfDtN7SYbfovgPDZhClbYBrx+rZqITJnXvW8Nx34lT4DdfHPvC9Rxys0qxOauQlBAP6f3mKoGd3LZFEMUJGGq52Ae3plHifI=
  - secure: j4u60MdVRK/WC5+9Bek6yhEB1fJwdlrumDJqNEsxGpRo+k+r4uF7bXRzMaUScYGQy/RhlEbtEUdJXToL5O0PkVVhT4okATrIGStEwNg+c1zQBXK1+fkgzc8/2FkTvT/oRQ7X/zMhmpmGXy+xG1scfQK+F1LSMgEfyfsH3Y4yCsHp65cycCFpL/m1mx3P8rk2gr+Z8zUYQFnXU98WX66eRpF5q2Vm2Gdze2b1oBLjo/z2GkF9yqddo35fvA6PJcMzVip0E6Y7s6itMbBAXYUoT/jBQES38sGvMy35dn12plTL18DGAj5ruLUyVg1gb1yGtZgX66s9NGKFIoMTg3e2sSgIWC0n8oqShSIYFE6k+TJGSyAZpEIiAcvRFrr2jVF1ozUqw7e/2FH0UZyzlSkeOdixfJfLWuQDSFcvwnj+YKW/nWGNleSJLM5AgsT2JcJ+UB74HCnvbVoLezruZN9T+rmSRMKAjC0KQsU+O160wlPtP8FkM8EnYtVGMZKBxitlnS7z2CBTC4LGNZZB6l/tOYR27bU+3n/phPthxZoEMpYiAUrX2tEcpHm+nTNrU3VitG03qbwU8RJND0H0wjoIMBh904mcu1/ZtXh+C2gKm7etGzRrT50RyeuZJu9j4SAB4RclJKeCK9NKN5kko1Bcq9q1nnHlwp6b3EF/NW0A3R8=
  - secure: JqsL0qy2de406c5goeARE2CHH4YkyESWsJQXn4a2IWxMXmgtX5jqA6AI3HzUfhn7pzp1zvJjPni8L2q+QnNk3kw/iB/7dDVBJBNdqt8VTHBDP9XpsC6qf5arhqifURsrR8grq37iWdCgKYRx7L/K1L58Gs4yQvTR7fcaIRoEaJhbJOW9LIZey118bMjXAa4WpHX/ifRw6ANlnVkviNKqTTNMRHWGvxgvQKTOx8dd4vLV9n46xDzQLzLuGgkTCaiUUV6Offrnt0HrBMdzV/vMlbdJKB0POxh5iEl3Eshct/oKKkD7ydrGC940gxpU6DWLq3PGLFhll8GrP3Kj2NR/Zqn8LeCLrwj/KScf9yV92QAknMsk8p5lwhF1jmLKo/jiCBVTdncNT1xJF3t6eb64AQhjeCEIARL8AAaUOC1SW2JsnBKDL6lACV5u1Tw4fHM/HdLQf7Rm/0/6bB3b4GwO2V8d8YwwpkwGNRuMHngYS8ui5mNRf9w3TpKl9gdW7v73x5mP35x5kgMibFP26zL7PNvGBzj44THWSZA7IwWCEACGF9whUVs8tlJtMB4BbZ3RSIr2+OBxmCDgR1ciBaPXmN0rsFmd+kKMJywdPozq59QO7AvP9I894fikxNdiGQ6kr60hzaMOPty5cVjlzClCrq+/1gv723++KYBIvCO28v0=
  - secure: vc1NODXTGFFW91yIW80zzeR1oFwgY3h+g5LjlzpQcEl6sVvF0IgaqtODemPELZqSnzjTZxcO3cAH9MYNo/2Cymi3pQkid6CulJ/p3utva9sKUXoa2xR3+RsjTUsKLHeMZ+/yEa9shuTRCmM7vwh9wxklNgMktjhDraa4uvCHuD8fDMtoPDN7pwtr6FXHMM2d8Iq5CvyzjqZl8aU9STd3AYJQ4lvXycORY0o5xnkrGUCXduXxs+r5LH8wrdo5mNdax3vqj9E/DreQh/nJPYGwFZjL1Srnyst9K6rBVPSogqPCfX2Xry3aIvdHvnymQgE39gwgaKtXt8IkRScZ06vaVXrO7GMC9W9PQXWGwsprtWWweLQDzvY06QHiPoMpTv1Ax6vh1AStcB2QBIcfbGEN9rzEb7ubE7saxQDc8GT2yoF14zT+PcOOR4NJGvpBa3k+fmDtmlQVaDx0+PWAQXkuXdh95LWWRCxzblWTguu5lzMnTvEu/BjQSjfR22PG9qY5cVnpZSCOAV6M1zrTEF/MP1WU6vowkDj9EqO5Ea37gMY1ersXByFnz/RMMeJx4byLrgJFTAcSXWQoIfD7zeqibtYAfTtGDn7l+DIJI8wn0D2sNkA2ixmag/V/0NCEdwAuctbnGfm4mhSW37k7o9LOl1axuZoMdw+lA069gg2gPsc=

  matrix:
    - ANDROID_TARGET=android-22
    - ANDROID_TARGET=android-19
    - ANDROID_TARGET=android-17
    - ANDROID_TARGET=android-15

android:
  components:
    - android-23
    - android-22
    - build-tools-23.0.1
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-19
    - sys-img-armeabi-v7a-android-17
    - sys-img-armeabi-v7a-android-15

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
    - ./gradlew --info clean lint :app:connectedAndroidTest
